config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to: "home#index"

  resources :merchants do
    post :upload_picture, on: :member
  end
  resources :inspect_merchants do
    post :change_status, :change_pay_route_status, :prepare_request,
          :update_backend_account, 
          :zx_infc, :pfb_infc, :create_pay_route, on: :member
    get :get_merchant_id, :get_backend_account, :routes, :add_route, on: :member
    resources :zx_contr_info_lists
  end
  namespace :user do
  	resources :sessions
    resources :password do
      post :reset_password, :send_reset_email, on: :collection
    end
    resources :confirmation
    resources :unlock
    resources :registrations
  end
  resources :users
  resources :upload_img, only: [:index]
  resources :error_logs do
    delete :destroy_all, on: :collection
  end
  namespace :api do
    resources :merchants
  end
  resources :test do
    get  :zx_appid, on: :collection 
    post :wechat_cert, on: :collection
  end
  resources :agents

end

app/controllers/inspect_merchants_controller.rb
# frozen_string_literal: true

class InspectMerchantsController < ResourcesController
  authorize_resource class: 'Merchant'
  before_action :authorize_current_user
  def authorize_current_user
    redirect_to '/' unless current_user.roles.pluck(:name).include?('admin')
  end

  def routes
    load_object
  end
  def add_route
    load_object
    @hash = {}
    @zx_response = @object.request_and_response.zx_response.deep_symbolize_keys rescue nil
    @hash[:zx_wechat_channel_mch_id] = @zx_response.deep_symbolize_keys[:wechat_query][:ROOT][:Mercht_Idtfy_Num] rescue nil
    @hash[:zx_alipay_channel_mch_id] = @zx_response.deep_symbolize_keys[:alipay_query][:ROOT][:Mercht_Idtfy_Num] rescue nil
    @pfb_response = @object.request_and_response.pfb_response.deep_symbolize_keys rescue nil
    query_customer_num = @pfb_response[:wechat_offline_查询][:customer][:customerNum] rescue nil
    response_customer_num = @pfb_response[:wechat_offline_新增][:customer_num] rescue nil
    @hash[:pfb_wechat_offline_channel_mch_id] = response_customer_num || query_customer_num
    query_api_key = @pfb_response[:wechat_offline_查询][:customer][:apiKey] rescue nil
    response_api_key = @pfb_response[:wechat_offline_新增][:api_key] rescue nil
    @hash[:pfb_wechat_offline_api_key] = response_api_key || query_api_key
    query_customer_num = @pfb_response[:alipay_查询][:customer][:customerNum] rescue nil
    response_customer_num = @pfb_response[:alipay_新增][:customer_num] rescue nil
    @hash[:pfb_alipay_channel_mch_id] = response_customer_num || query_customer_num
    query_api_key = @pfb_response[:alipay_查询][:customer][:apiKey] rescue nil
    response_api_key = @pfb_response[:alipay_新增][:api_key] rescue nil
    @hash[:pfb_alipay_api_key] = response_api_key || query_api_key
  end

  def update
    load_object

    super
  end

  def change_status
    load_object
    if @object.update(status: Merchant::STATUS_DATA.invert[params[:status]])
      flash[:success] = '状态修改成功'
    else
      flash[:error] = "未知状态：#{params[:status]}"
    end
    redirect_to action: :show, id: @object.id
  end
  def change_pay_route_status
    load_object
    if @object.pay_route_status.update("#{params[:route]}": Merchant::PAY_ROUTE_STATUS_DATA.invert[params[:status]])
      flash[:success] = '状态修改成功'
    else
      flash[:error] = "未知状态：#{params[:status]}"
    end
    redirect_to action: :show, id: @object.id
  end

  def prepare_request
    load_object
    zx_biz = Biz::ZxMctInfo.new @object
    pfb_biz = Biz::PfbMctInfo.new @object
    if !zx_biz.prepare_request || !pfb_biz.prepare_request
      flash[:error] = '数据生成报错！'
    else
      flash[:success] = '数据生成成功！点击“查询支付渠道信息”查看详情'
    end
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end
  def get_backend_account
    load_object
    core_account = Biz::CoreAccount.new(@object)
    # pay_route = Biz::PayRoute::PayRouteBase.new @object
    unless @object.merchant_id.present?
      flash[:error] = "merchant_id为空"
    else
      @result = core_account.get_backend_account # 提交创建请求
      # pay_route.query
    end

    if core_account.has_error
      flash[:error] = core_account.error_message
    else
      $redis.set("result_#{@object.id}", @result)
      $redis.pexpire("result_#{@object.id}", 60 * 1000 )
    end
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end

  # def update_backend_account
  #   load_object
  #   core_account = Biz::CoreAccount.new(@object)
  #   if @object.merchant_id.present?
  #     if core_account.update_backend_account
  #       flash[:success] = '数据获取成功！'
  #     else
  #       flash[:error] = core_account.error_message
  #     end
  #   elsif !core_account.create_backend_account
  #     flash[:error] = core_account.error_message
  #   else
  #     flash[:success] = '数据生成成功！'
  #   end
  #   redirect_to action: :show, id: @object.id.to_s
  # rescue Exception => e
  #   flash[:error] = e.message
  #   log_error @object, e.message, '', e.backtrace, params
  #   redirect_to action: :show, id: @object.id.to_s
  # end
  def get_merchant_id
    load_object
    core_account = Biz::CoreAccount.new(@object)
    if @object.merchant_id.present?
      flash[:success] = 'merchant_id已经存在！'
    else
      @result = core_account.create_backend_account
      $redis.set("result_#{@object.id}", @result)
      $redis.pexpire("result_#{@object.id}", 60 * 1000 )
    end
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end

  def zx_infc
    load_object
    bz = Biz::ZxInfcApi.new(@object, params[:channel])
    result = bz.send_intfc(params[:req_typ])
    if result
      $redis.set("result_#{@object.id}", result)
      $redis.pexpire("result_#{@object.id}", 60 * 1000 )
    else
      flash[:error] = bz.error_message
    end
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end

  def pfb_infc
    load_object
    bz = Biz::PfbInfcApi.new(@object.id, params[:channel])
    result = bz.send_intfc(params[:req_typ])
    if result
      $redis.set("result_#{@object.id}", result)
      $redis.pexpire("result_#{@object.id}", 60 * 1000 )
    else
      flash[:error] = bz.error_message
    end
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end

  def create_pay_route
    load_object
    case params[:route]
    when 'bjrcb.wechat_offline'
      biz = Biz::PayRoute::BjrcbPayRoute.new @object, params[:channel_type]
      @result = biz.send_wechat_offline
    when 'bjrcb.alipay'
      biz = Biz::PayRoute::BjrcbPayRoute.new @object, params[:channel_type]
      @result = biz.send_alipay
    when 'CITIC_WECHAT'
      biz = Biz::PayRoute::ZxAlipayPayRoute.new @object
      @result = biz.send_wechat
    when 'CITIC_ALI'
      biz = Biz::PayRoute::ZxAlipayPayRoute.new @object
      @result = biz.send_alipay
    end
    $redis.set("result_#{@object.id}", @result)
    $redis.pexpire("result_#{@object.id}", 60 * 1000 )
    redirect_to action: :show, id: @object.id.to_s
  rescue Exception => e
    flash[:error] = e.message
    log_error @object, e.message, '', e.backtrace, params
    redirect_to action: :show, id: @object.id.to_s
  end


  def load_object
    @object = Merchant.find(params[:id])
    raise "can't find Merchant by id #{params[:id]}" unless @object.present?
  end
  def object_name
    "merchant"
  end
end

app/views/inspect_merchants/_filter.slim
.filter-wrap.collapsed
  = form_for(:q, html: {class: 'search-filter form-inline', method: 'get'}) do |f|
    .form-group.m-r-10
      = text_field_tag 'q[name]', params[:q][:name], placeholder: '商户名称', class: 'form-control'

    .form-group.m-r-10
      = text_field_tag 'q[merchant_id]', params[:q][:merchant_id], placeholder: 'merchant_id', class: 'form-control'

    .form-group.m-r-10
      = text_field_tag 'q[partner_mch_id]', params[:q][:partner_mch_id], placeholder: 'partner_mch_id', class: 'form-control'

    .form-group.m-r-10
      = submit_tag '查找', class: 'btn btn-sm btn-primary m-r-5'

app/views/inspect_merchants/add_route.html.erb
<input id="merchant_id" type="" name="" value="<%= @object.merchant_id %>" class="hidden">
<input id="index" type="" name="" value="<%= routes_inspect_merchant_path(@object.id) %>" class="hidden">
<div class="body">

    <div id="add">
        <div class="form-group col-xs-12">
            <div class="col-xs-offset-3 col-xs-6">
                <%= text_area_tag 'req_body', JSON.pretty_generate(@hash), style: 'height: 180px;', class: 'form-control', disabled: 'disabled' %>
            </div>
        </div>
        <form action="" class="form-horizontal col-xs-offset-2" id="addform">
            <div class="form-group">
                <label for="" class="col-xs-3 control-label">渠道密钥</label>
                <div class="col-xs-4" id="channel-key">
                    <input type="text" class="form-control input-sm" name="channel-key">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-xs-3 control-label">渠道名称</label>
                <div class="col-xs-2">
                    <select name="" class="form-control input-sm " id="channel-name">
                            <option class ="paytype" value="SWIFT">威富通</option>
                            <option class ="paytype" value="BJRCB">北京农商行</option>
                            <option class ="paytype" value="CITIC_ALI">中信直连支付宝</option>
                            <option class ="paytype" value="CITIC_WECHAT">中信直连微信</option>
                            <option class ="paytype" value="DIANZI">点子</option>
                            <option class ="paytype" value="TFB">天付宝</option>
                            <option class ="paytype" value="SOFTBANKC">大连软银</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-xs-3 control-label">渠道商户号</label>
                <div class="col-xs-4" id="channel-mch-id">
                    <input type="text" class="form-control input-sm">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-xs-3 control-label">路由状态</label>
                <div class="col-xs-2">
                    <select name="" class="form-control input-sm" id="priority">
                        <option value="1">开启</option>
                        <option value="0">关闭</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-xs-3 control-label">渠道类型</label>
                <div class="col-xs-2">
                    <select name="" class="form-control input-sm channel-mch-id" id="channel-type">
                        <option value="1">T1</option>
                        <option value="0">D0</option>
                    </select>
                </div>
            </div>
            <label for="" class="col-xs-3 control-label">支付方式</label>
            <div class="col-xs-3 pay-type" id="pay-type">
                <label class="checkbox-inline ">
                   <input type="checkbox" value="wechat.scan" name="pay" checked="checked" class="SWIFT BJRCB CITIC_WECHAT"> wechat.scan
                </label>
                <label class="checkbox-inline ">
                    <input type="checkbox" value="alipay.scan" name="pay" checked="checked" class="SWIFT BJRCB CITIC_ALI"> alipay.scan
                 </label>
                <label class="checkbox-inline">
                      <input type="checkbox"value="qq.scan" name="pay" checked="checked" class="SWIFT"> qq.scan
                </label>
                <br/>
                <label class="checkbox-inline">
                      <input type="checkbox" value="wechat.jsapi" name="pay" checked="checked" class="SWIFT CITIC_WECHAT"> wechat.jsapi
                </label>
                <label class="checkbox-inline">
                      <input type="checkbox"  value="alipay.jsapi" name="pay" checked="checked" class="SWIFT CITIC_ALI"> alipay.jsapi
                </label>
                <label class="checkbox-inline">
                    <input type="checkbox" value="qq.jsapi" name="pay" checked="checked" class="SWIFT"> qq.jsapi
                </label>
                <br/>
                <label class="checkbox-inline">
                    <input type="checkbox"  value="wechat.micro" name="pay" checked="checked" class="SWIFT BJRCB CITIC_WECHAT"> wechat.micro
                </label>
                <label class="checkbox-inline">
                    <input type="checkbox" value="alipay.micro" name="pay" checked="checked"  class="SWIFT BJRCB CITIC_ALI"> alipay.micro
                </label>
                <label class="checkbox-inline">
                    <input type="checkbox" value="qq.micro" name="pay" checked="checked" class="SWIFT"> qq.micro
                </label>
                <br/>
                <label class="checkbox-inline">
                     <input type="checkbox" value="wechat.jsurl" name="pay" class="BJRCB"> wechat.jsurl
                 </label>
            </div>

            <div class="hide" id="city">
                <h3 class="title"></h3>
                <div class="form-group">
                    <label for="" class="col-xs-3 control-label" value="">服务商appid</label>
                    <div class="col-xs-4" id="CITIC_appid">
                        <input type="text" class="form-control input-sm">
                    </div>
                </div>
                <div class="hide" id="cityWeChat">
                    <div class="form-group">
                        <label for="" class="col-xs-3 control-label" value="">服务商秘钥</label>
                        <div class="col-xs-4" id="CITIC_wekey">
                            <input type="text" class="form-control input-sm">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-xs-3 control-label" value="">服务商商户号</label>
                        <div class="col-xs-4" id="CITIC_wenum">
                            <input type="text" class="form-control input-sm">
                        </div>
                    </div>
                </div>
                <div id="cityali" class="hide">
                    <div class="form-group">
                        <label for="" class="col-xs-3 control-label" value="">支付宝token</label>
                        <div class="col-xs-4" id="CITIC_ali">
                            <input type="text" class="form-control input-sm">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text-center">
                    <a class="btn btn-primary btn-lg addbtn"> 添 加 </a>
                    <%= link_to '返回', routes_inspect_merchant_path(@object.id), class: 'btn btn-default btn-lg'%>
                </div>
            </div>
        </form>
    </div>
</div>

app/views/inspect_merchants/edit.slim
= link_to '经营类目对照表', 'http://note.youdao.com/share/index.html?id=8d75d1b9b21c46675efac97f3ebe0b4b&type=note#/', target: '_blank', class: 'btn btn-link'

= horizon_form_for @object, url: url_for(controller: "inspect_merchants", action: :update)  do |f|
  = render 'shared/base', f: f
  br
  br
  = render 'shared/zx_contr_info_lists', f: f
  br
  = render 'shared/pfb_contr_info_lists', f: f
  br
  = render 'shared/relate_pictures', f: f
  br
  br
  .row
    .col-xs-11.text-right
      = f.submit '修改', class: 'btn btn-lg btn-success'
javascript:
  $(document).ready(function(){ 
  　　$('.form-horizontal').attr('action', "/inspect_merchants/#{@object.id}" )
  }); 
  

app/views/inspect_merchants/index.slim
= link_to '查看说明文档', 'https://note.youdao.com/share/?token=0E8D25D2AC2F4E8FAB3E6A7E3D3A1727&gid=45230067', target: '_blank', class: 'btn btn-link'
= render 'filter'

table.table
  tr
    th 商户编号
    th 商户类型
    th 商户名称
    th 商户状态
    th 代理商
    th 操作
  - @collection.each do |obj|
    tr
      td= obj.merchant_id
      td= obj.mch_type
      td= obj.name
      td= Merchant::STATUS_DATA[obj.status]
      td= obj.user.partner_id
      td
        = link_to '编辑', edit_inspect_merchant_url(obj.id.to_s), class: 'btn btn-sm btn-primary'
        = link_to '查看', inspect_merchant_url(obj.id.to_s), class: 'btn btn-sm btn-default'
        - if obj.merchant_id.present?
          = link_to '路由信息', routes_inspect_merchant_path(obj.id), class: 'btn btn-sm btn-default'
        = link_to '锁定数据', change_status_inspect_merchant_url(obj.id.to_s, status: '审核中'), method: :post, class: 'btn btn-sm btn-warning'
= will_paginate @collection 

app/views/inspect_merchants/show.slim
.row
  .col-xs-9
    = text_area_tag 'req_body', JSON.pretty_generate(@object.inspect(true)), style: 'height: 800px;', class: 'form-control'
    .col-xs-12
      .col-xs-3
        h4
          | 法人身份证正面
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.identity_card_front_key), class: 'image'
      .col-xs-3
        h4
          | 法人身份证反面
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.identity_card_back_key), class: 'image'
      .col-xs-3
        h4
          | 法人手持身份证
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.id_with_hand_key), class: 'image'
      .col-xs-3
        h4
          | 营业执照
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.license_key), class: 'image'
    .col-xs-12
      .col-xs-3
        h4
          | 店铺照
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.shop_picture_key), class: 'image'
      .col-xs-3
        h4
          | 银行卡正面
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.bank_info.right_bank_card_key), class: 'image'
      .col-xs-3
        h4
          | （法人）银行开户许可证
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.account_licence_key), class: 'image'


  .col-xs-3
    br
    .box.box-primary
      .box-body
        p= "当前状态：#{Merchant::STATUS_DATA[@object.status]}"
        p
          = link_to '审核失败', change_status_inspect_merchant_url(@object.id.to_s, status: '审核失败'), method: :post, class: 'btn btn-lg btn-danger'
          | &nbsp
          = link_to '锁定数据', change_status_inspect_merchant_url(@object.id.to_s, status: '审核中'), method: :post, class: 'btn btn-lg btn-warning'
          | &nbsp
          = link_to '审核通过', change_status_inspect_merchant_url(@object.id.to_s, status: '审核通过'), method: :post, class: 'btn btn-lg btn-success'
          | &nbsp
          = link_to '商户停用', change_status_inspect_merchant_url(@object.id.to_s, status: '商户停用'), method: :post, class: 'btn btn-lg btn-default'
        p
          - if @object.pay_route_status.t1_status == 0
            = link_to '开通T1', change_pay_route_status_inspect_merchant_url(@object.id.to_s, status: '已开通', route: 't1_status'), method: :post, class: 'btn btn-lg btn-success'
          - else
            = link_to '关闭T1', change_pay_route_status_inspect_merchant_url(@object.id.to_s, status: '未开通', route: 't1_status'), method: :post, class: 'btn btn-lg btn-warning'
          | &nbsp
          - if @object.pay_route_status.d0_status == 0
            = link_to '开通D0', change_pay_route_status_inspect_merchant_url(@object.id.to_s, status: '已开通', route: 'd0_status'), method: :post, class: 'btn btn-lg btn-success'
          - else
            = link_to '关闭D0', change_pay_route_status_inspect_merchant_url(@object.id.to_s, status: '未开通', route: 'd0_status'), method: :post, class: 'btn btn-lg btn-warning'
        p
          = link_to '编辑', edit_inspect_merchant_url(@object.id.to_s), class: 'btn btn-lg btn-primary'
          | &nbsp
          - if @object.merchant_id.present?
            = link_to '路由信息', routes_inspect_merchant_path(@object.id), class: 'btn btn-lg btn-default'
            | &nbsp
          = link_to '生成进件请求', prepare_request_inspect_merchant_url(@object.id.to_s), method: :post, class: 'btn btn-lg btn-default'
          - if !@object.merchant_id.present?
            | &nbsp
            = link_to '获取merchant_id', get_merchant_id_inspect_merchant_path(@object.id.to_s), class: 'btn btn-lg btn-default'
          - if @object.merchant_id.present?
            | &nbsp
            = link_to '查询merchant信息', get_backend_account_inspect_merchant_path(@object.id.to_s), class: 'btn btn-lg btn-default'
            | &nbsp
            - link_to '修改支付渠道信息', update_backend_account_inspect_merchant_path(@object.id.to_s), method: :post, class: 'btn btn-lg btn-default'
    br
    .box
      .box-header
        h4.box-title 中信微信
      .box-body
        = link_to '停用', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '停用', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-danger'
        | &nbsp
        = link_to '进件', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '新增', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-warning'
        | &nbsp
        = link_to '查询', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-success'
        | &nbsp
        = link_to '变更', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '变更', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-primary'
        | &nbsp
        = link_to '提交支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'CITIC_WECHAT'), method: :post, class: 'btn btn-lg btn-default'
        p
          = link_to '创建appid', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '创建appid', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-default'
          = link_to '查询appid', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询appid', channel: 'wechat'), method: :post, class: 'btn btn-lg btn-default'
    br
    .box
      .box-header
        h4.box-title 中信支付宝
      .box-body
        = link_to '停用', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '停用', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-danger'
        | &nbsp
        = link_to '进件', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '新增', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-warning'
        | &nbsp
        = link_to '查询', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-success'
        | &nbsp
        = link_to '变更', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '变更', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-primary'
        | &nbsp
        = link_to '提交支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'CITIC_ALI'), method: :post, class: 'btn btn-lg btn-default'
    br
    .box
      .box-header
        h4.box-title 农商微信线下
      .box-body
        = link_to '进件', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '新增', channel: 'wechat_offline'), method: :post, class: 'btn btn-lg btn-warning'
        | &nbsp
        = link_to '查询', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询', channel: 'wechat_offline'), method: :post, class: 'btn btn-lg btn-success'
        | &nbsp
        = link_to '变更', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '变更', channel: 'wechat_offline'), method: :post, class: 'btn btn-lg btn-primary'
        | &nbsp
        = link_to '提交T1支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'bjrcb.wechat_offline', channel_type: '1'), method: :post, class: 'btn btn-lg btn-default'
        | &nbsp
        = link_to '提交D0支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'bjrcb.wechat_offline', channel_type: '0'), method: :post, class: 'btn btn-lg btn-default'
    /br
    /.box
      /.box-header
        /h4.box-title 农商微信App
      /.box-body
        /= link_to '进件', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '新增', channel: 'wechat_app'), method: :post, class: 'btn btn-lg btn-warning'
        /| &nbsp
        /= link_to '查询', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询', channel: 'wechat_app'), method: :post, class: 'btn btn-lg btn-success'
        /| &nbsp
        /= link_to '变更', zx_infc_inspect_merchant_url(@object.id.to_s, req_typ: '变更', channel: 'wechat_app'), method: :post, class: 'btn btn-lg btn-primary'
    br
    .box
      .box-header
        h4.box-title 农商支付宝
      .box-body
        = link_to '进件', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '新增', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-warning'
        | &nbsp
        = link_to '查询', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '查询', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-success'
        | &nbsp
        = link_to '变更', pfb_infc_inspect_merchant_url(@object.id.to_s, req_typ: '变更', channel: 'alipay'), method: :post, class: 'btn btn-lg btn-primary'
        | &nbsp
        = link_to '提交T1支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'bjrcb.alipay', channel_type: '1'), method: :post, class: 'btn btn-lg btn-default'
        | &nbsp
        = link_to '提交D0支付路由', create_pay_route_inspect_merchant_url(@object.id.to_s, route: 'bjrcb.alipay', channel_type: '0'), method: :post, class: 'btn btn-lg btn-default'