config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to: "home#index"

  resources :merchants do
    post :upload_picture, on: :member
  end
  resources :inspect_merchants do
    post :change_status, :change_pay_route_status, :prepare_request,
          :update_backend_account, 
          :zx_infc, :pfb_infc, :create_pay_route, on: :member
    get :get_merchant_id, :get_backend_account, :routes, :add_route, on: :member
    resources :zx_contr_info_lists
  end
  namespace :user do
  	resources :sessions
    resources :password do
      post :reset_password, :send_reset_email, on: :collection
    end
    resources :confirmation
    resources :unlock
    resources :registrations
  end
  resources :users
  resources :upload_img, only: [:index]
  resources :error_logs do
    delete :destroy_all, on: :collection
  end
  namespace :api do
    resources :merchants
  end
  resources :test do
    get  :zx_appid, on: :collection 
    post :wechat_cert, on: :collection
  end
  resources :agents

end

app/views/shared/_base.slim
.row
  .col-xs-6
    .box
      .box-header
        h4.box-title 基本信息
      .box-body
        = f.input :partner_mch_id
        = f.input :full_name
        = f.input :name
        = f.input :memo
        = f.input :mch_type do
          = f.select :mch_type, ['个体','企业'], include_blank: true
        = f.input :province
        = f.input :urbn
        = f.input :zone
        = f.input :address
        = f.input :appid, placeholder: '三选一'
        = f.input :jsapi_path, placeholder: '三选一'
        = f.input :subscribe_appid, placeholder: '三选一'
        = f.input :industry
        = f.input :mch_deal_type
        = f.input :d0_rate
        = f.input :t1_rate
        = f.input :fixed_fee
        = f.input :alipay_channel_type_lv1
        = f.input :alipay_channel_type_lv2
        = f.input :wechat_channel_type_lv2

    .box
      .box-header
        h4.box-title 公司信息
      .box-body
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 联系人电话
          .col-sm-9
            = text_field_tag 'merchant[company][contact_tel]', @object.company[:contact_tel], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 联系人姓名
          .col-sm-9
            = text_field_tag 'merchant[company][contact_name]', @object.company[:contact_name], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 客服电话
          .col-sm-9
            = text_field_tag 'merchant[company][service_tel]', @object.company[:service_tel], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 联系人邮箱
          .col-sm-9
            = text_field_tag 'merchant[company][contact_email]', @object.company[:contact_email], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 营业执照编码
          .col-sm-9
            = text_field_tag 'merchant[company][license_code]', @object.company[:license_code], class: "form-control string optional"

  .col-xs-6
    .box
      .box-header
        h4.box-title 银行信息
      .box-body
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 开户人姓名/公司名
          .col-sm-9
            = text_field_tag 'merchant[bank_info][owner_name]', @object.bank_info[:owner_name], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 支付联行号
          .col-sm-9
            = text_field_tag 'merchant[bank_info][bank_sub_code]', @object.bank_info[:bank_sub_code], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 账号
          .col-sm-9
            = text_field_tag 'merchant[bank_info][account_num]', @object.bank_info[:account_num], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 账户类型(对私，对公)
          .col-sm-9
            = select_tag 'merchant[bank_info][account_type]', options_for_select( ['对私', '对公'],@object.bank_info[:account_type]), class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 持卡人身份证号码
          .col-sm-9
            = text_field_tag 'merchant[bank_info][owner_idcard]', @object.bank_info[:owner_idcard], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 开户省
          .col-sm-9
            = text_field_tag 'merchant[bank_info][province]', @object.bank_info[:province], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 开户市
          .col-sm-9
            = text_field_tag 'merchant[bank_info][urbn]', @object.bank_info[:urbn], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 开户区
          .col-sm-9
            = text_field_tag 'merchant[bank_info][zone]', @object.bank_info[:zone], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 银行全称
          .col-sm-9
            = text_field_tag 'merchant[bank_info][bank_full_name]', @object.bank_info[:bank_full_name], class: "form-control string optional"

    .box
      .box-header
        h4.box-title 法人信息
      .box-body
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 法人姓名
          .col-sm-9
            = text_field_tag 'merchant[legal_person][name]', @object.legal_person[:name], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 法人电话
          .col-sm-9
            = text_field_tag 'merchant[legal_person][tel]', @object.legal_person[:tel], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 法人email
          .col-sm-9
            = text_field_tag 'merchant[legal_person][email]', @object.legal_person[:email], class: "form-control string optional"
        .form-group.string.optional.merchant_address
          label.col-sm-3.control-label.string.optional 法人身份证号
          .col-sm-9
            = text_field_tag 'merchant[legal_person][identity_card_num]', @object.legal_person[:identity_card_num], class: "form-control string optional"

app/views/shared/_edit_dialog.slim
.modal.fade id="edit_dialog_div"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4.modal-title 交互
      .modal-body
        = text_area_tag 'body', $redis.get("result_#{@object.id}"), style: 'height: 600px;',class: 'form-control'
      .modal-footer
        a.btn.btn-sm.btn-white data-dismiss="modal" href="javascript:;"  关闭
- $redis.pexpire("result_#{@object.id}", 0)

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |k,v| %>
    <div class="box box-solid box-<%= ['error','alert'].include?(k.to_s) ? 'danger' : k.to_s %>">
      <div class="box-header with-border">
        <h3 class="box-title"><%= k.to_s.capitalize %></h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div><!-- /.box-tools -->
      </div><!-- /.box-header -->
      <div class="box-body">
        <%== v %>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  <% end %>
<% end %>

app/views/shared/_index_table_options.html.erb
<% if collection.respond_to? :total_pages %>
  <%= will_paginate collection, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/shared/_pfb_contr_info_lists.slim
.row
  .col-xs-12
    .box
      .box-header
        h4.box-title 农商行渠道信息
      .box-body
        table.table.table-bordered
          thead
            tr
              th 支付类型
              th 支付类型费率(%)
              th 是否开通T0
              th T0费率(%)
              th T0单笔加收费用(元)
              th 是否封顶
              th 封顶值(元)
              th 结算模式
          tbody
            - {'微信线下': 'wechat_offline', '支付宝': 'alipay'}.each do |key,value|
              tr
                td = key
                td
                	= text_field_tag "merchant[channel_data][pfb][#{value}][rate]", @object.channel_data['pfb'].try(:[], value).try(:[],'rate'), style: 'width: 80px;'
                td
                  = select_tag "merchant[channel_data][pfb][#{value}][t0Status]", options_for_select( {'开通': 'Y', '关闭': 'N'},  @object.channel_data['pfb'].try(:[], value).try(:[],'t0Status')), class: "form-control string optional",include_blank: true
                td
                  = text_field_tag "merchant[channel_data][pfb][#{value}][settleRate]", @object.channel_data['pfb'].try(:[], value).try(:[],'settleRate'), style: 'width: 80px;'
                td
                  = text_field_tag "merchant[channel_data][pfb][#{value}][fixedFee]", @object.channel_data['pfb'].try(:[], value).try(:[],'fixedFee'), style: 'width: 80px;'
                td
                  = select_tag "merchant[channel_data][pfb][#{value}][isCapped]", options_for_select( {'是': 'Y', '否': 'N'},  @object.channel_data['pfb'].try(:[], value).try(:[],'isCapped')), class: "form-control string optional",include_blank: true
                td
                  = text_field_tag "merchant[channel_data][pfb][#{value}][upperFee]", @object.channel_data['pfb'].try(:[], value).try(:[],'upperFee'), style: 'width: 80px;'
                td
                  = select_tag "merchant[channel_data][pfb][#{value}][settleMode]", options_for_select( Biz::PfbMctInfo::SettleModes,  @object.channel_data['pfb'].try(:[], value).try(:[],'settleMode')), class: "form-control string optional",include_blank: true

app/views/shared/_relate_pictures.html.slim
.row
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 法人身份证正面token
      .box-body
        = text_field_tag 'merchant[legal_person][identity_card_front_key]', @object.legal_person.identity_card_front_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.identity_card_front_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 法人身份证反面token
      .box-body
        = text_field_tag 'merchant[legal_person][identity_card_back_key]', @object.legal_person.identity_card_back_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.identity_card_back_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 法人手持身份证token
      .box-body
        = text_field_tag 'merchant[legal_person][id_with_hand_key]', @object.legal_person.id_with_hand_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.legal_person.id_with_hand_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 营业执照token
      .box-body
        = text_field_tag 'merchant[company][license_key]', @object.company.license_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.license_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 店铺照token
      .box-body
        = text_field_tag 'merchant[company][shop_picture_key]', @object.company.shop_picture_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.shop_picture_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 银行卡正面token
      .box-body
        = text_field_tag 'merchant[bank_info][right_bank_card_key]', @object.bank_info.right_bank_card_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.bank_info.right_bank_card_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title （法人）银行开户许可证token
      .box-body
        = text_field_tag 'merchant[company][account_licence_key]', @object.company.account_licence_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.account_licence_key), class: 'image'
  .col-xs-3
    .box.box-success
      .box-header
        h4.box-title 组织机构代码照token
      .box-body
        = text_field_tag 'merchant[company][org_photo_key]', @object.company.org_photo_key
        = image_tag qiniu_or_noimage(@object.user.bucket_url,@object.company.org_photo_key), class: 'image'
        

app/views/shared/_zx_contr_info_lists.slim
.row
  .col-xs-12
    .box
      .box-header
        h4.box-title 中信渠道信息
      .box-body
        table.table.table-bordered
          thead
            tr
              th 支付类型
              th 支付类型费率
              th 费率生效日期
              th 操作
          tbody
            - @object.zx_contr_info_lists.each do |obj|
              tr
                td= ZxContrInfoList::PayTypData[obj.pay_typ_encd]
                td= obj.pay_typ_fee_rate
                td= obj.start_dt
                td
                  = link_to '编辑', edit_inspect_merchant_zx_contr_info_list_path(inspect_merchant_id: params[:id], id: obj.id.to_s), class: 'btn btn-sm btn-primary'
                  = link_to '删除', "/inspect_merchants/#{params[:id]}/zx_contr_info_lists/#{obj.id.to_s}", method: :delete, class: 'btn btn-sm btn-danger'

        br
        .col-xs-11.text-right
          = link_to '增加渠道', new_inspect_merchant_zx_contr_info_list_path(inspect_merchant_id: params[:id]), class: 'btn btn-success'