config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root to: "home#index"

  resources :merchants do
    post :upload_picture, on: :member
  end
  resources :inspect_merchants do
    post :change_status, :change_pay_route_status, :prepare_request,
          :update_backend_account, 
          :zx_infc, :pfb_infc, :create_pay_route, on: :member
    get :get_merchant_id, :get_backend_account, :routes, :add_route, on: :member
    resources :zx_contr_info_lists
  end
  namespace :user do
  	resources :sessions
    resources :password do
      post :reset_password, :send_reset_email, on: :collection
    end
    resources :confirmation
    resources :unlock
    resources :registrations
  end
  resources :users
  resources :upload_img, only: [:index]
  resources :error_logs do
    delete :destroy_all, on: :collection
  end
  namespace :api do
    resources :merchants
  end
  resources :test do
    get  :zx_appid, on: :collection 
    post :wechat_cert, on: :collection
  end
  resources :agents

end

app/views/layouts/_footer.html.slim
<!-- Main Footer -->
footer.main-footer
  .pull-right.hidden-xs
    | 商户进件系统
  strong
    | 深圳市普尔瀚达科技有限公司

app/views/layouts/_header.html.slim
<!-- Main Header -->
header.main-header

  <!-- Logo -->
  = link_to root_path, class: 'logo' do
    <!-- mini logo for sidebar mini 50x50 pixels -->
    span.logo-mini
      b
        | P
      | ool
    <!-- logo for regular state and mobile devices -->
    span.logo-lg
      b
        | 普尔云
      | 进件系统

  <!-- Header Navbar -->
  nav.navbar.navbar-static-top role="navigation"
    <!-- Sidebar toggle button-->
    a.sidebar-toggle href="#" class="" data-toggle="offcanvas" role="button"
      span.sr-only
        | Toggle navigation
    <!-- Navbar Right Menu -->
    .navbar-custom-menu
      ul.nav.navbar-nav
        <!-- Messages: style can be found in dropdown.less-->

        <!-- User Account Menu -->
        - if current_user
          li.dropdown.user.user-menu
            <!-- Menu Toggle Button -->
            a.dropdown-toggle data-toggle="dropdown"
              <!-- The user image in the navbar-->
              = image_tag 'no-img.png', class: 'user-image'
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              span.hidden-xs
                = current_user.email
            ul.dropdown-menu
              <!-- The user image in the menu -->
              li.user-header
                = image_tag 'no-img.png', class: 'user-circle'
                p
                  b
                    = current_user.email
                  br
                  = current_user.roles.pluck(:name).join(',')
                    small
                      = current_user.created_at.to_date
              <!-- Menu Footer-->
              li.user-footer
                .pull-left
                  = link_to "注册信息", edit_user_registration_path(session[:user_id]),  class: "btn btn-default btn-flat"
                .pull-right
                  = link_to "登出", "/user/sessions/#{session[:user_id]}", :method => :delete, class: "btn btn-default btn-flat"

app/views/layouts/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">



    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">功能</li>
      <!-- Optionally, you can add icons to the links -->
      <% if can?(:index, Merchant) %>
      <li class="<%= controller_name == 'merchants' ? 'active' : '' %>">
        <%= link_to merchants_path do %>
          <i class="fa fa-link"></i> <span>商户管理</span>
        <% end %>
      </li>
      <% end %>
      <% if can?(:index, :inspect_merchants) %>
      <li class="<%= controller_name == 'inspect_merchants' ? 'active' : '' %>">
        <%= link_to inspect_merchants_path do %>
          <i class="fa fa-link"></i> <span>审核</span>
        <% end %>
      </li>
      <% end %>
      <% if can?(:index, User) %>
      <li class="<%= controller_name == 'uses' ? 'active' : '' %>">
        <%= link_to users_path do %>
          <i class="fa fa-link"></i> <span>管理用户</span>
        <% end %>
      </li>
      <% end %>
      <% if can?(:index, Agent) %>
      <li class="<%= controller_name == 'uses' ? 'active' : '' %>">
        <%= link_to agents_path do %>
          <i class="fa fa-link"></i> <span>管理代理商</span>
        <% end %>
      </li>
      <% end %>
      <li class="<%= controller_name == 'upload_img' ? 'active' : '' %>">
        <%= link_to upload_img_index_path, target: '_blank' do %>
          <i class="fa fa-link"></i> <span>上传图片</span>
        <% end %>
      </li>
      <% if can?(:index, ErrorLog) %>
      <li class="<%= controller_name == 'error_logs' ? 'active' : '' %>">
        <%= link_to error_logs_path, target: '_blank' do %>
          <i class="fa fa-link"></i> <span>错误信息</span>
        <% end %>
      </li>
      <% end %>
      <% if can?(:index, :test) %>
      <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>测试</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="#"></a>
            <%= link_to zx_appid_test_index_path do %>
              ZxAppid
            <% end %>
          </li>
        </ul>
      </li>
      <% end %>
      <%#<li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>%>
      <%#<li class="treeview">%>
        <%#<a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>%>
          <%#<span class="pull-right-container">%>
            <%#<i class="fa fa-angle-left pull-right"></i>%>
          <%#</span>%>
        <%#</a>%>
        <%#<ul class="treeview-menu">%>
          <%#<li><a href="#">Link in level 2</a></li>%>
          <%#<li><a href="#">Link in level 2</a></li>%>
        <%#</ul>%>
      <%#</li>%>
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>商户信息管理</title>
    <%= csrf_meta_tags %>
    <!-- Ionicons -->
  	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  	<!--[if lt IE 9]>
  	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  	<![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  </head>
	<!--
	BODY TAG OPTIONS:
	=================
	Apply one or more of the following classes to get the
	desired effect
	|---------------------------------------------------------|
	| SKINS         | skin-blue                               |
	|               | skin-black                              |
	|               | skin-purple                             |
	|               | skin-yellow                             |
	|               | skin-red                                |
	|               | skin-green                              |
	|---------------------------------------------------------|
	|LAYOUT OPTIONS | fixed                                   |
	|               | layout-boxed                            |
	|               | layout-top-nav                          |
	|               | sidebar-collapse                        |
	|               | sidebar-mini                            |
	|---------------------------------------------------------|
	-->
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render :partial => "/layouts/header" %>
      <%= render :partial => "/layouts/sidebar" %>
  		<!-- Content Wrapper. Contains page content -->
  		<div class="content-wrapper">
  		  <!-- Content Header (Page header) -->
  		  <section class="content-header">
  		    <h1>
            <%= I18n.translate(controller_name) %>
  		      <small><%= I18n.translate(action_name) %></small>
  		    </h1>
  		    <ol class="breadcrumb">
            <li>
              <a href="<%= url_for(action: 'index') rescue '###' %>">
                <i class="fa fa-dashboard"></i><%= I18n.translate(controller_name) %>
              </a>
            </li>
            <li class="active"><%= I18n.translate(action_name) %></li>
  		    </ol>
  		  </section>

  		  <!-- Main content -->
  		  <section class="content">
          <%= render :partial => "/shared/flash" %>
          <%= render :partial => "/shared/edit_dialog" if @object.present? && $redis.get("result_#{@object.id}").present?   %>
  		    <!-- Your Page Content Here -->
					<%= yield %>
  		  </section>
  		  <!-- /.content -->
  		</div>
  		<!-- /.content-wrapper -->
      <%= render :partial => "/layouts/footer" %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
		<!-- ./wrapper -->
		<!-- REQUIRED JS SCRIPTS -->
		<!-- AdminLTE App -->
    <!-- file_upload -->
    <%#<script src="/plugins/file_upload/js/vendor/jquery.ui.widget.js"></script>%>
    <%#<script src="/plugins/file_upload/js/jquery.iframe-transport.js"></script>%>
    <%#<script src="/plugins/file_upload/js/jquery.fileupload.js"></script>%>
    <%#<script src="/plugins/file_upload/my_fileuploader.js"></script>%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>商户信息管理</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>商户信息管理 | 登录</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../plugins/iCheck/square/blue.css">

  	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  	<!--[if lt IE 9]>
  	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  	<![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <%= link_to root_path do %>
          <b>商户信息管理</b>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <!-- REQUIRED JS SCRIPTS -->
		<!-- jQuery 2.2.3 -->
		<script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
		<!-- Bootstrap 3.3.6 -->
		<script src="/bootstrap/js/bootstrap.min.js"></script>
		<!-- AdminLTE App -->
    <!-- iCheck -->
    <script src="/plugins/iCheck/icheck.min.js"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>商户信息管理 | 登录</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <%= link_to root_path do %>
          <b>商户信息管理</b>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>